In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("shop_sales_messy.csv")

df.head()

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,Discount_%,PaymentMethod,Region
0,ORD16652,2026-06-05,Lucy Achieng,Soda 500ml,Beverages,14.0,79.12,0.0,Visa/Card,nakuru
1,ORD14124,2024-07-29,Peter Cheruiyot,Toothpaste,Personal Care,2.0,151.16,0.0,Cash,NAIROBI
2,ORD12242,2025-11-25,Faith Gitau,Cooking Gas Re fill 6kg,Household,2.0,1358.01,0.0,cash,eldoret
3,ORD16474,2024/02/21,Ruth Mwangi,TOOTHPASTE,Personal Care,14.0,160.88,0.0,Cash,MOMBASA
4,ORD16243,06-29-2026,NaN,Biscuits,Snacks,2.0,90.19,0.0,Cash,Eldoret

In [3]:
df.shape

(9048, 10)

In [4]:
df.columns

Index(['OrderID', 'Date', 'CustomerName', 'Product', 'Category', 'Quantity',
       'UnitPrice', 'Discount_%', 'PaymentMethod', 'Region'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9048 entries, 0 to 9047
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        9040 non-null   object
 1   Date           8659 non-null   object
 2   CustomerName   8211 non-null   object
 3   Product        9040 non-null   object
 4   Category       9040 non-null   object
 5   Quantity       8814 non-null   float64
 6   UnitPrice      8857 non-null   object
 7   Discount_%     9040 non-null   float64
 8   PaymentMethod  9040 non-null   object
 9   Region         9040 non-null   object
dtypes: float64(2), object(8)
memory usage: 707.0+ KB

In [6]:
df.describe(include="all")

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,Discount_%,PaymentMethod,Region
count,9040,8659,8211,9040,9040,8814.000000,8857,9040.000000,9040,9040
unique,9000,3956,201,99,9,NaN,7320,NaN,16,19
top,ORD16121,2026-06-18,Samuel Mutua,Soda 500ml,Groceries,NaN,KES 59,NaN,CARD,Thika
freq,2,9,58,333,1830,NaN,8,NaN,635,536
mean,NaN,NaN,NaN,NaN,NaN,7.255503,NaN,1.193031,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,4.595182,NaN,4.047212,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-14.000000,NaN,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,0.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,7.000000,NaN,0.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,0.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,14.000000,NaN,20.000000,NaN,NaN

In [7]:
df.isnull().sum()

OrderID            8
Date             389
CustomerName     837
Product            8
Category           8
Quantity         234
UnitPrice        191
Discount_%         8
PaymentMethod      8
Region             8
dtype: int64

In [8]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

CustomerName     9.250663
Date             4.299293
Quantity         2.586207
UnitPrice        2.110964
OrderID          0.088417
Product          0.088417
Category         0.088417
Discount_%       0.088417
PaymentMethod    0.088417
Region           0.088417
dtype: float64

In [9]:
df.duplicated().sum()

np.int64(47)

In [10]:
df[df.duplicated()]

,OrderID,Date,CustomerName,Product,Category,Quantity,UnitPrice,Discount_%,PaymentMethod,Region
608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1065,ORD16121,02/02/2024,Joyce Rono,Sugar 2kg,Groceries,10.0,286.38,0.0,Card,NAKURU
1502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2181,ORD15916,21-Mar-2026,Esther Mutua,Maize Flour 2kg,Groceries,10.0,190.52,0.0,Visa/Card,thika
2327,ORD15291,27-Dec-2025,Joyce Wanjiru,Earphones,Electronics,2.0,514.01,0.0,cash,Thika
2604,ORD12510,2026-07-28,James Wanjiru,Bic Pen,Stationery,8.0,18.19,0.0,CASH,Eldoret
2644,ORD10950,2026/08/30,Daniel Otieno,Milk 500ml,Dairy,14.0,61.41,10.0,Card,mombasa
2697,ORD12419,13/08/2024,Victor Cheruiyot,Maize Flour 2kg,Groceries,14.0,NaN,0.0,M-PESA,Nakuru
2901,ORD14870,2025-06-21,Michael Cheruiyot,Cooking Gas Refill 6kg,Household,7.0,"KES 1,158",0.0,Card,eldoret
3151,ORD12498,07/08/2026,Kevin Cheruiyot,Bic Pen,Stationery,4.0,20.93,15.0,cash,Kisumu
3195,ORD14286,2024-03-23,Ruth Cheruiyot,Phone Charger,Electronics,5.0,349.27,0.0,CASH,thika
3691,ORD12568,19/09/2024,John Rono,umbrella,Household,13.0,378.09,10.0,Card,Eldoret
3740,ORD17195,2024-06-18,James Otieno,Cooking Gas Refill 6kg,Household,NaN,1225.07,0.0,Visa/Card,NAIROBI
4185,ORD10104,2024/02/13,Ruth Cheruiyot,airtime scratch card,Electronics,10.0,94.81,5.0,m-pesa,NAIROBI
4371,ORD12778,23/07/2024,Esther Wanjiru,COOKING OIL 1L,Groceries,10.0,355.1,0.0,cash,Thika
4412,ORD10130,2025-11-15,Michael Kiplagat,Soda 500ml,Beverages,6.0,76.76,5.0,Mpesa,Nakuru
4480,ORD15277,10-Sep-2025,Lucy Mutua,Cooking Gas Refill 6kg,Household,12.0,1371.37,0.0,CASH,Nairobi
4632,ORD16346,13/09/2024,Lucy Mwangi,Bottled Water 500ml,Beverages,NaN,55.75,0.0,CASH,Mombasa
4800,ORD12961,2024-06-02,James Rono,Sweets Packet,Snacks,9.0,30.45,0.0,Cash,nakuru
5122,ORD10578,2025-03-29,Brian Kiplagat,COOKING GAS REFILL 6KG,Household,12.0,1245.17,0.0,cash,nairobi
5160,ORD16653,07/01/2026,NaN,UMBRELLA,Household,14.0,422.3,20.0,CASH,nakuru
5520,ORD10736,06/08/2025,Lucy Wanjiru,Bottled Water 500ml,Beverages,7.0,45.72,5.0,cash,Eldoret
5791,ORD12264,2025/11/04,Michael Rono,Phone Charger,Electronics,8.0,372.65,0.0,Card,Eldoret
5908,ORD14826,2025-02-02,James Achieng,Earphones,Electronics,13.0,405.32,0.0,cash,kisumu
6022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6024,ORD13080,2025-09-22,Daniel Cheruiyot,maize flour 2kg,Groceries,7.0,211.33,0.0,Cash,Kisumu
6033,ORD18902,2025-08-04,NaN,COOKING OIL 1L,Groceries,7.0,315.38,5.0,CARD,Eldoret
6183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6459,ORD10309,2026/03/01,Ruth Cheruiyot,Sweets Packet,Snacks,4.0,28.82,0.0,CARD,Nairobi
6612,ORD16492,NaN,Daniel Otieno,Biscuits,Snacks,11.0,89.48,0.0,Card,nakuru
6785,ORD18999,08-07-2025,Esther Achieng,Toothpaste,Personal Care,7.0,135.37,0.0,card,mombasa
6883,ORD12429,09/12/2024,NaN,Airtime Scratch Card,Electronics,3.0,109.15,10.0,card,Mombasa
6916,ORD14524,2024-01-30,Michael Mwangi,Sugar 2kg,Groceries,10.0,238.6,10.0,card,Nakuru
6980,ORD10053,2024/04/21,Mary Otieno,Toothpaste,Personal Care,5.0,170.31,0.0,Visa/Card,eldoret
7152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7438,ORD14260,01-05-2024,NaN,Bottled Water 500ml,Beverages,5.0,53.88,0.0,Mpesa,Eldoret
7588,ORD17028,07-Jan-2026,Ruth Gitau,MILK 500ML,Dairy,4.0,65.86,0.0,M-Pesa,Eldoret
7665,ORD17189,11/03/2024,Mary Otieno,Cooking Gas Refill 6kg,Household,3.0,"KES 1,132",0.0,CARD,Nairobi
7804,ORD18509,2026-08-08,Peter Njoroge,Bottled Water 500ml,Beverages,4.0,55.2,0.0,MPESA,Nairobi
7979,ORD11616,09-Jul-2024,John Mwangi,Bread,Bakery,9.0,60.88,0.0,Cash,kisumu
8433,ORD15873,2024/09/23,Faith Otieno,bread,Bakery,9.0,62.18,0.0,mpesa,Nairobi
8481,ORD18846,2025-02-26,Catherine Cheruiyot,cooking gas refill 6kg,Household,2.0,1206.56,0.0,M-PESA,Eldoret
8591,ORD12071,2025/12/19,Mary Rono,Cooking Oil 1L,Groceries,3.0,298.98,0.0,CARD,Kisumu
8696,ORD17086,2026-05-04,Samuel Cheruiyot,earphones,Electronics,7.0,484.39,20.0,mpesa,MOMBASA
8782,ORD12108,02-28-2026,Faith Mwangi,Exercise Book,Stationery,1.0,45.67,0.0,Card,Nairobi
8886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_raw = df.copy()

In [12]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 9001

In [13]:
#Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("%", "percent")
)

df.columns

Index(['orderid', 'date', 'customername', 'product', 'category', 'quantity',
       'unitprice', 'discount_percent', 'paymentmethod', 'region'],
      dtype='object')

In [14]:
#Clean text Columns
text_columns = [
    "customername",
    "product",
    "category",
    "paymentmethod",
    "region"
]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

In [15]:
#standardize Customer names
df["customername"] = df["customername"].str.title()

In [16]:
#replace missing names with unknown
df["customername"] = df["customername"].fillna("Unknown")

In [17]:
#standardiz product names
df["product"] = df["product"].str.title()

In [18]:
sorted(df["product"].dropna().unique())

['Airtime  Scratch Card',
 'Airtime Scratch Card',
 'Bic Pe N',
 'Bic Pen',
 'Biscuits',
 'Bottle D Water 500Ml',
 'Bottled Water 500Ml',
 'Bre Ad',
 'Bread',
 'Cooking Gas Re Fill 6Kg',
 'Cooking Gas Refill 6Kg',
 'Cooking Oil 1L',
 'De Tergent 1Kg',
 'Detergent 1Kg',
 'Earphone S',
 'Earphones',
 'Exe Rcise Book',
 'Exercise Book',
 'Maize  Flour 2Kg',
 'Maize Flour 2Kg',
 'Milk 500Ml',
 'Phone  Charger',
 'Phone Charger',
 'Rice  2Kg',
 'Rice 2Kg',
 'Soap Bar',
 'Soda 500Ml',
 'Sugar 2Kg',
 'Swe Ets Packet',
 'Sweets Packet',
 'Toothpaste',
 'Umbre Lla',
 'Umbrella']

In [20]:
#Product with suspicious spaces
df[df["product"].str.contains(r"\s{2,}", na=False)]["product"].unique()

<StringArray>
[]
Length: 0, dtype: string

In [21]:
df["product"] = df["product"].str.replace(r"\s+", " ", regex=True)

In [22]:
df["category"].value_counts(dropna=False)

category
Groceries        1822
Household        1785
Electronics      1333
Beverages         927
Stationery        915
Snacks            877
Dairy             452
Personal Care     446
Bakery            443
<NA>                1
Name: count, dtype: Int64

In [23]:
df["category"] = df["category"].str.strip().str.title()

In [24]:
df["paymentmethod"].value_counts(dropna=False)

paymentmethod
Cash         1194
cash         1176
Card         1132
CARD          631
CASH          611
card          596
Visa/Card     581
mpesa         530
Mpesa         529
m-pesa        517
M-Pesa        510
MPESA         503
M-PESA        490
<NA>            1
Name: count, dtype: Int64

In [25]:
payment_mapping = {
    "cash": "Cash",
    "card": "Card",
    "visa/card": "Card",
    "mpesa": "M-Pesa",
    "m-pesa": "M-Pesa"
}

df["paymentmethod"] = (
    df["paymentmethod"]
    .str.lower()
    .str.strip()
    .replace(payment_mapping)
)

In [26]:
df["paymentmethod"].value_counts(dropna=False)

paymentmethod
M-Pesa    3079
Cash      2981
Card      2940
<NA>         1
Name: count, dtype: Int64

In [27]:
df["paymentmethod"] = df["paymentmethod"].fillna("Unknown")

In [28]:
df["region"] = df["region"].str.strip().str.title()

In [29]:
df["region"].value_counts(dropna=False)

region
Thika      1576
Eldoret    1547
Nairobi    1474
Mombasa    1474
Kisumu     1472
Nakuru     1457
<NA>          1
Name: count, dtype: Int64

In [30]:
df["region"] = df["region"].fillna("Unknown")

In [31]:
#convert date to time
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

In [32]:
#Date range
print("Earliest date:", df["date"].min())
print("Latest date:", df["date"].max())

Earliest date: 2024-01-01 00:00:00
Latest date: 2026-09-14 00:00:00

In [33]:
df["quantity"] = pd.to_numeric(
    df["quantity"],
    errors="coerce"
)

In [34]:
df["quantity"].describe()

count    8776.000000
mean        7.253988
std         4.598710
min       -14.000000
25%         4.000000
50%         7.000000
75%        11.000000
max        14.000000
Name: quantity, dtype: float64

In [35]:
df[df["quantity"] < 0]

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region
114,ORD16904,2026-02-22,Faith Mwangi,Bottled Water 500Ml,Beverages,-3.0,46.24,0.0,Cash,Thika
304,ORD16202,NaT,Unknown,Bread,Bakery,-13.0,68.25,0.0,M-Pesa,Nairobi
325,ORD12733,2024-09-28,Peter Kiplagat,Bic Pen,Stationery,-7.0,22.24,0.0,Card,Nairobi
359,ORD14407,NaT,Peter Mwangi,Umbrella,Household,-8.0,376.38,0.0,M-Pesa,Nakuru
383,ORD10162,NaT,Faith Kiplagat,Detergent 1Kg,Household,-3.0,199.16,0.0,Cash,Kisumu
...,...,...,...,...,...,...,...,...,...,...
8994,ORD15085,NaT,Lucy Cheruiyot,Airtime Scratch Card,Electronics,-4.0,112.26,0.0,Card,Nakuru
9016,ORD10764,NaT,Joyce Njoroge,Milk 500Ml,Dairy,-4.0,55.36,0.0,Cash,Kisumu
9022,ORD17651,2024-12-22,Mary Gitau,Detergent 1Kg,Household,-2.0,NaN,10.0,M-Pesa,Mombasa
9031,ORD17955,NaT,Esther Gitau,Airtime Scratch Card,Electronics,-6.0,110.5,0.0,M-Pesa,Thika
9047,ORD10537,NaT,David Achieng,Sugar 2Kg,Groceries,-8.0,273.91,0.0,Card,Thika

In [36]:
(df["quantity"] < 0).sum()

np.int64(186)

In [37]:
df["unitprice"] = (
    df["unitprice"]
    .astype("string")
    .str.replace("KES", "", regex=False)
    .str.strip()
)

In [38]:
df["unitprice"].describe()

count     8818
unique    7320
top         55
freq         8
Name: unitprice, dtype: object

In [39]:
df["discount_percent"] = pd.to_numeric(
    df["discount_percent"],
    errors="coerce"
)

In [40]:
df["discount_percent"].describe()

count    9000.000000
mean        1.185556
std         4.038240
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        20.000000
Name: discount_percent, dtype: float64

In [41]:
df[df["quantity"] < 0]

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region
114,ORD16904,2026-02-22,Faith Mwangi,Bottled Water 500Ml,Beverages,-3.0,46.24,0.0,Cash,Thika
304,ORD16202,NaT,Unknown,Bread,Bakery,-13.0,68.25,0.0,M-Pesa,Nairobi
325,ORD12733,2024-09-28,Peter Kiplagat,Bic Pen,Stationery,-7.0,22.24,0.0,Card,Nairobi
359,ORD14407,NaT,Peter Mwangi,Umbrella,Household,-8.0,376.38,0.0,M-Pesa,Nakuru
383,ORD10162,NaT,Faith Kiplagat,Detergent 1Kg,Household,-3.0,199.16,0.0,Cash,Kisumu
...,...,...,...,...,...,...,...,...,...,...
8994,ORD15085,NaT,Lucy Cheruiyot,Airtime Scratch Card,Electronics,-4.0,112.26,0.0,Card,Nakuru
9016,ORD10764,NaT,Joyce Njoroge,Milk 500Ml,Dairy,-4.0,55.36,0.0,Cash,Kisumu
9022,ORD17651,2024-12-22,Mary Gitau,Detergent 1Kg,Household,-2.0,<NA>,10.0,M-Pesa,Mombasa
9031,ORD17955,NaT,Esther Gitau,Airtime Scratch Card,Electronics,-6.0,110.5,0.0,M-Pesa,Thika
9047,ORD10537,NaT,David Achieng,Sugar 2Kg,Groceries,-8.0,273.91,0.0,Card,Thika

In [43]:
df[
    (df["discount_percent"] < 0) |
    (df["discount_percent"] > 100)
]

Empty DataFrame
Columns: [orderid, date, customername, product, category, quantity, unitprice, discount_percent, paymentmethod, region]
Index: []

In [46]:
df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce")
df["unitprice"] = pd.to_numeric(df["unitprice"], errors="coerce")

In [47]:
df["sales_amount"] = df["quantity"] * df["unitprice"]

In [48]:
df[["quantity", "unitprice", "sales_amount"]].head()

   quantity  unitprice  sales_amount
0      14.0      79.12       1107.68
1       2.0     151.16        302.32
2       2.0    1358.01       2716.02
3      14.0     160.88       2252.32
4       2.0      90.19        180.38

In [49]:
df["discount_amount"] = (
    df["sales_amount"] *
    df["discount_percent"] / 100
)

In [50]:
df["net_sales"] = (
    df["sales_amount"] -
    df["discount_amount"]
)

In [51]:
df.head()

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
0,ORD16652,2026-06-05,Lucy Achieng,Soda 500Ml,Beverages,14.0,79.12,0.0,Card,Nakuru,1107.68,0.0,1107.68
1,ORD14124,2024-07-29,Peter Cheruiyot,Toothpaste,Personal Care,2.0,151.16,0.0,Cash,Nairobi,302.32,0.0,302.32
2,ORD12242,2025-11-25,Faith Gitau,Cooking Gas Re Fill 6Kg,Household,2.0,1358.01,0.0,Cash,Eldoret,2716.02,0.0,2716.02
3,ORD16474,NaT,Ruth Mwangi,Toothpaste,Personal Care,14.0,160.88,0.0,Cash,Mombasa,2252.32,0.0,2252.32
4,ORD16243,NaT,Unknown,Biscuits,Snacks,2.0,90.19,0.0,Cash,Eldoret,180.38,0.0,180.38

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9001 entries, 0 to 9047
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   orderid           9000 non-null   object
 1   date              2262 non-null   datetime64[ns]
 2   customername      9001 non-null   string
 3   product           9000 non-null   string
 4   category          9000 non-null   string
 5   quantity          8776 non-null   float64
 6   unitprice         8786 non-null   Float64
 7   discount_percent  9000 non-null   float64
 8   paymentmethod     9001 non-null   string
 9   region            9001 non-null   string
 10  sales_amount      8566 non-null   Float64
 11  discount_amount   8566 non-null   Float64
 12  net_sales         8566 non-null   Float64
dtypes: Float64(4), datetime64[ns](1), float64(2), object(1), string(5)
memory usage: 1019.6+ KB

In [53]:
df.isnull().sum()

orderid                1
date                6739
customername           0
product                1
category               1
quantity             225
unitprice            215
discount_percent       1
paymentmethod          0
region                 0
sales_amount         435
discount_amount      435
net_sales            435
dtype: int64

In [54]:
null_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

null_summary = null_summary[null_summary["Missing_Count"] > 0]

null_summary.sort_values("Missing_Count", ascending=False)

                  Missing_Count  Missing_Percentage
date                       6739               74.87
sales_amount                435                4.83
discount_amount             435                4.83
net_sales                   435                4.83
quantity                    225                2.50
unitprice                   215                2.39
orderid                       1                0.01
product                       1                0.01
category                      1                0.01
discount_percent              1                0.01

In [55]:
df["customername"] = df["customername"].fillna("Unknown")

In [56]:
df["category"] = df["category"].fillna("Unknown")

In [57]:
df["paymentmethod"] = df["paymentmethod"].fillna("Unknown")

In [58]:
df["region"] = df["region"].fillna("Unknown")

In [59]:
df[df["product"].isnull()]

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
506,NaN,NaT,Unknown,<NA>,Unknown,NaN,<NA>,NaN,Unknown,Unknown,<NA>,<NA>,<NA>

In [60]:
df["product"] = df["product"].fillna("Unknown")

In [61]:
df[df["date"].isnull()].head(20)

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
3,ORD16474,NaT,Ruth Mwangi,Toothpaste,Personal Care,14.0,160.88,0.0,Cash,Mombasa,2252.32,0.0,2252.32
4,ORD16243,NaT,Unknown,Biscuits,Snacks,2.0,90.19,0.0,Cash,Eldoret,180.38,0.0,180.38
5,ORD14087,NaT,Daniel Achieng,Maize Flour 2Kg,Groceries,9.0,201.33,0.0,Cash,Nakuru,1811.97,0.0,1811.97
6,ORD12567,NaT,Mary Kiplagat,Airtime Scratch Card,Electronics,1.0,110.86,0.0,Card,Thika,110.86,0.0,110.86
7,ORD11421,NaT,Samuel Otieno,Soda 500Ml,Beverages,14.0,74.29,0.0,Cash,Kisumu,1040.06,0.0,1040.06
8,ORD18653,NaT,Peter Cheruiyot,Bread,Bakery,4.0,67.83,0.0,M-Pesa,Nairobi,271.32,0.0,271.32
9,ORD17550,NaT,John Mutua,Exercise Book,Stationery,2.0,42.51,0.0,Card,Thika,85.02,0.0,85.02
10,ORD15826,NaT,Faith Rono,Detergent 1Kg,Household,2.0,191.25,0.0,Cash,Thika,382.5,0.0,382.5
11,ORD17176,NaT,Faith Wanjiru,Bread,Bakery,5.0,72.74,0.0,M-Pesa,Nakuru,363.7,0.0,363.7
12,ORD15525,NaT,Samuel Njoroge,Detergent 1Kg,Household,4.0,209.25,0.0,Card,Nakuru,837.0,0.0,837.0
13,ORD16502,NaT,John Otieno,Umbrella,Household,10.0,455.71,0.0,Cash,Mombasa,4557.1,0.0,4557.1
14,ORD11680,NaT,Joyce Wanjiru,Rice 2Kg,Groceries,1.0,305.9,20.0,Cash,Nairobi,305.9,61.18,244.72
15,ORD13150,NaT,David Mutua,Sugar 2Kg,Groceries,12.0,285.91,0.0,M-Pesa,Mombasa,3430.92,0.0,3430.92
16,ORD18703,NaT,Unknown,Umbrella,Household,2.0,440.28,0.0,Cash,Kisumu,880.56,0.0,880.56
17,ORD13773,NaT,Michael Njoroge,Phone Charger,Electronics,11.0,337.75,10.0,Cash,Nakuru,3715.25,371.525,3343.725
19,ORD10345,NaT,Victor Mutua,Maize Flour 2Kg,Groceries,2.0,182.41,0.0,M-Pesa,Mombasa,364.82,0.0,364.82
20,ORD11324,NaT,Ruth Mutua,Detergent 1Kg,Household,NaN,220.43,0.0,Cash,Kisumu,<NA>,<NA>,<NA>
21,ORD13210,NaT,Brian Achieng,Detergent 1Kg,Household,7.0,193.0,0.0,Card,Kisumu,1351.0,0.0,1351.0
22,ORD11010,NaT,Faith Cheruiyot,Rice 2Kg,Groceries,NaN,253.18,0.0,Cash,Nakuru,<NA>,<NA>,<NA>
23,ORD12531,NaT,Kevin Njoroge,Bread,Bakery,2.0,59.22,10.0,M-Pesa,Nakuru,118.44,11.844,106.596

In [62]:
df[df["quantity"].isnull()][
    ["orderid", "product", "category", "unitprice"]
].head(20)

      orderid              product     category  unitprice
20   ORD11324        Detergent 1Kg    Household     220.43
22   ORD11010             Rice 2Kg    Groceries     253.18
130  ORD15177              Bic Pen   Stationery      21.01
135  ORD16346  Bottled Water 500Ml    Beverages      55.75
186  ORD15441              Bic Pen   Stationery      20.31
232  ORD17088            Earphones  Electronics     423.58
256  ORD10421           Milk 500Ml        Dairy      68.75
286  ORD13916             Umbrella    Household     416.27
296  ORD18369             Biscuits       Snacks      82.85
336  ORD17075             Umbrella    Household     372.62
392  ORD16807             Rice 2Kg    Groceries     308.62
402  ORD17921            Earphones  Electronics     498.43
421  ORD18805        Phone Charger  Electronics     370.97
506       NaN              Unknown      Unknown       <NA>
518  ORD13219  Bottled Water 500Ml    Beverages      56.79
520  ORD11683       Cooking Oil 1L    Groceries     318.57
534  ORD16909        Phone Charger  Electronics     366.02
575  ORD10221             Rice 2Kg    Groceries     259.24
576  ORD16269        Phone Charger  Electronics      371.7
610  ORD10901        Phone Charger  Electronics      390.0

In [63]:
df[df["unitprice"].isnull()][
    ["orderid", "product", "category", "quantity"]
].head(20)

      orderid                  product     category  quantity
161  ORD14045                    Bread       Bakery      14.0
196  ORD11791                Sugar 2Kg    Groceries      14.0
219  ORD14382                    Bread       Bakery       1.0
242  ORD18480               Milk 500Ml        Dairy      11.0
302  ORD15673  Cooking Gas Re Fill 6Kg    Household       4.0
305  ORD10488     Airtime Scratch Card  Electronics       5.0
365  ORD12419          Maize Flour 2Kg    Groceries      14.0
396  ORD12281               Soda 500Ml    Beverages     -13.0
443  ORD11995   Cooking Gas Refill 6Kg    Household       5.0
506       NaN                  Unknown      Unknown       NaN
517  ORD15058   Cooking Gas Refill 6Kg    Household      13.0
528  ORD15957            Exercise Book   Stationery       3.0
533  ORD17266   Cooking Gas Refill 6Kg    Household       2.0
545  ORD15318   Cooking Gas Refill 6Kg    Household       9.0
568  ORD15343   Cooking Gas Refill 6Kg    Household      11.0
642  ORD11136                 Umbrella    Household      10.0
680  ORD12161                Sugar 2Kg    Groceries       3.0
712  ORD16765      Bottled Water 500Ml    Beverages       9.0
838  ORD16238               Soda 500Ml    Beverages      11.0
896  ORD16329            Exercise Book   Stationery       6.0

In [64]:
df[df["discount_percent"].isnull()][
    ["orderid", "product", "quantity", "unitprice"]
]

    orderid  product  quantity  unitprice
506     NaN  Unknown       NaN       <NA>

In [65]:
df["discount_percent"] = df["discount_percent"].fillna(0)

In [66]:
df["sales_amount"] = df["quantity"] * df["unitprice"]

In [67]:
df[["quantity", "unitprice", "sales_amount", "net_sales"]].isnull().sum()

quantity        225
unitprice       215
sales_amount    435
net_sales       435
dtype: int64

In [68]:
null_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

null_summary = null_summary[null_summary["Missing_Count"] > 0]

null_summary.sort_values("Missing_Count", ascending=False)

                 Missing_Count  Missing_Percentage
date                      6739               74.87
sales_amount               435                4.83
discount_amount            435                4.83
net_sales                  435                4.83
quantity                   225                2.50
unitprice                  215                2.39
orderid                      1                0.01

In [69]:
df[df["orderid"].isnull()]

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
506,NaN,NaT,Unknown,Unknown,Unknown,NaN,<NA>,0.0,Unknown,Unknown,<NA>,<NA>,<NA>

In [70]:
df[["quantity", "unitprice", "sales_amount"]].isnull().sum()

quantity        225
unitprice       215
sales_amount    435
dtype: int64

In [72]:
df[df["date"].isnull()][
    ["orderid", "customername", "product", "category",
     "quantity", "unitprice", "paymentmethod", "region"]
].head(20)

,orderid,customername,product,category,quantity,unitprice,paymentmethod,region
3,ORD16474,Ruth Mwangi,Toothpaste,Personal Care,14.0,160.88,Cash,Mombasa
4,ORD16243,Unknown,Biscuits,Snacks,2.0,90.19,Cash,Eldoret
5,ORD14087,Daniel Achieng,Maize Flour 2Kg,Groceries,9.0,201.33,Cash,Nakuru
6,ORD12567,Mary Kiplagat,Airtime Scratch Card,Electronics,1.0,110.86,Card,Thika
7,ORD11421,Samuel Otieno,Soda 500Ml,Beverages,14.0,74.29,Cash,Kisumu
8,ORD18653,Peter Cheruiyot,Bread,Bakery,4.0,67.83,M-Pesa,Nairobi
9,ORD17550,John Mutua,Exercise Book,Stationery,2.0,42.51,Card,Thika
10,ORD15826,Faith Rono,Detergent 1Kg,Household,2.0,191.25,Cash,Thika
11,ORD17176,Faith Wanjiru,Bread,Bakery,5.0,72.74,M-Pesa,Nakuru
12,ORD15525,Samuel Njoroge,Detergent 1Kg,Household,4.0,209.25,Card,Nakuru
13,ORD16502,John Otieno,Umbrella,Household,10.0,455.71,Cash,Mombasa
14,ORD11680,Joyce Wanjiru,Rice 2Kg,Groceries,1.0,305.9,Cash,Nairobi
15,ORD13150,David Mutua,Sugar 2Kg,Groceries,12.0,285.91,M-Pesa,Mombasa
16,ORD18703,Unknown,Umbrella,Household,2.0,440.28,Cash,Kisumu
17,ORD13773,Michael Njoroge,Phone Charger,Electronics,11.0,337.75,Cash,Nakuru
19,ORD10345,Victor Mutua,Maize Flour 2Kg,Groceries,2.0,182.41,M-Pesa,Mombasa
20,ORD11324,Ruth Mutua,Detergent 1Kg,Household,NaN,220.43,Cash,Kisumu
21,ORD13210,Brian Achieng,Detergent 1Kg,Household,7.0,193.0,Card,Kisumu
22,ORD11010,Faith Cheruiyot,Rice 2Kg,Groceries,NaN,253.18,Cash,Nakuru
23,ORD12531,Kevin Njoroge,Bread,Bakery,2.0,59.22,M-Pesa,Nakuru

In [71]:
df[
    df["quantity"].isnull() |
    df["unitprice"].isnull()
][
    ["quantity", "unitprice", "sales_amount"]
].head(20)

     quantity  unitprice  sales_amount
20        NaN     220.43          <NA>
22        NaN     253.18          <NA>
130       NaN      21.01          <NA>
135       NaN      55.75          <NA>
161      14.0       <NA>          <NA>
186       NaN      20.31          <NA>
196      14.0       <NA>          <NA>
219       1.0       <NA>          <NA>
232       NaN     423.58          <NA>
242      11.0       <NA>          <NA>
256       NaN      68.75          <NA>
286       NaN     416.27          <NA>
296       NaN      82.85          <NA>
302       4.0       <NA>          <NA>
305       5.0       <NA>          <NA>
336       NaN     372.62          <NA>
365      14.0       <NA>          <NA>
392       NaN     308.62          <NA>
396     -13.0       <NA>          <NA>
402       NaN     498.43          <NA>

In [73]:
df_raw["Date"].head(20)

0      2026-06-05
1      2024-07-29
2      2025-11-25
3      2024/02/21
4      06-29-2026
5      07-29-2024
6      2026/02/20
7      04-11-2026
8      04-01-2025
9      2025/05/22
10     01-17-2025
11     2025/09/27
12     20/10/2025
13    22-Aug-2026
14     2024/01/19
15     13/06/2025
16     17/06/2024
17     2024/04/15
18     2025-12-02
19     2025/01/21
Name: Date, dtype: object

In [74]:
df_raw["Date"].isnull().sum()

np.int64(389)

In [75]:
df["date"] = pd.to_datetime(
    df_raw["Date"].astype("string").str.strip(),
    errors="coerce",
    format="mixed"
)

df["date"].isnull().sum()

np.int64(381)

In [76]:
bad_dates = df_raw.loc[
    df["date"].isna() & df_raw["Date"].notna(),
    "Date"
]

bad_dates

Series([], Name: Date, dtype: object)

In [77]:
print("Missing dates in original data:", df_raw["Date"].isna().sum())
print("Missing dates in cleaned data:", df["date"].isna().sum())
print("Rows removed as duplicates:", len(df_raw) - len(df))

Missing dates in original data: 389
Missing dates in cleaned data: 381
Rows removed as duplicates: 47

In [78]:
null_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

null_summary = null_summary[
    null_summary["Missing_Count"] > 0
]

null_summary.sort_values(
    "Missing_Count",
    ascending=False
)

                 Missing_Count  Missing_Percentage
sales_amount               435                4.83
discount_amount            435                4.83
net_sales                  435                4.83
date                       381                4.23
quantity                   225                2.50
unitprice                  215                2.39
orderid                      1                0.01

In [79]:
df[df["orderid"].isna()]

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
506,NaN,NaT,Unknown,Unknown,Unknown,NaN,<NA>,0.0,Unknown,Unknown,<NA>,<NA>,<NA>

In [80]:
df = df.drop(index=506)

In [81]:
df.isnull().sum()

orderid               0
date                380
customername          0
product               0
category              0
quantity            224
unitprice           214
discount_percent      0
paymentmethod         0
region                0
sales_amount        434
discount_amount     434
net_sales           434
dtype: int64

In [82]:
df[df["quantity"].isna()][
    ["orderid", "customername", "product", "category", "quantity", "unitprice"]
].head(20)

,orderid,customername,product,category,quantity,unitprice
20,ORD11324,Ruth Mutua,Detergent 1Kg,Household,NaN,220.43
22,ORD11010,Faith Cheruiyot,Rice 2Kg,Groceries,NaN,253.18
130,ORD15177,Peter Otieno,Bic Pen,Stationery,NaN,21.01
135,ORD16346,Lucy Mwangi,Bottled Water 500Ml,Beverages,NaN,55.75
186,ORD15441,Mary Njoroge,Bic Pen,Stationery,NaN,20.31
232,ORD17088,David Cheruiyot,Earphones,Electronics,NaN,423.58
256,ORD10421,Daniel Gitau,Milk 500Ml,Dairy,NaN,68.75
286,ORD13916,David Achieng,Umbrella,Household,NaN,416.27
296,ORD18369,Mary Mutua,Biscuits,Snacks,NaN,82.85
336,ORD17075,Michael Njoroge,Umbrella,Household,NaN,372.62
392,ORD16807,David Gitau,Rice 2Kg,Groceries,NaN,308.62
402,ORD17921,Michael Mwangi,Earphones,Electronics,NaN,498.43
421,ORD18805,Naomi Rono,Phone Charger,Electronics,NaN,370.97
518,ORD13219,Esther Cheruiyot,Bottled Water 500Ml,Beverages,NaN,56.79
520,ORD11683,Catherine Otieno,Cooking Oil 1L,Groceries,NaN,318.57
534,ORD16909,Esther Njoroge,Phone Charger,Electronics,NaN,366.02
575,ORD10221,Kevin Achieng,Rice 2Kg,Groceries,NaN,259.24
576,ORD16269,Lucy Achieng,Phone Charger,Electronics,NaN,371.7
610,ORD10901,Grace Mutua,Phone Charger,Electronics,NaN,390.0
634,ORD17638,Victor Njoroge,Cooking Oil 1L,Groceries,NaN,349.08

In [83]:
df[df["quantity"].isna()]["unitprice"].isna().value_counts()

unitprice
False    220
True       4
Name: count, dtype: int64

In [84]:
df[df["unitprice"].isna()].head(10)

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales
161,ORD14045,2024-04-21,Kevin Kiplagat,Bread,Bakery,14.0,<NA>,0.0,Cash,Nairobi,<NA>,<NA>,<NA>
196,ORD11791,2024-11-26,Unknown,Sugar 2Kg,Groceries,14.0,<NA>,10.0,Card,Thika,<NA>,<NA>,<NA>
219,ORD14382,2024-02-07,Ann Mwangi,Bread,Bakery,1.0,<NA>,0.0,Card,Kisumu,<NA>,<NA>,<NA>
242,ORD18480,2026-08-21,Daniel Otieno,Milk 500Ml,Dairy,11.0,<NA>,0.0,Card,Eldoret,<NA>,<NA>,<NA>
302,ORD15673,2025-11-17,Grace Wanjiru,Cooking Gas Re Fill 6Kg,Household,4.0,<NA>,0.0,Card,Kisumu,<NA>,<NA>,<NA>
305,ORD10488,2026-03-10,Michael Kiplagat,Airtime Scratch Card,Electronics,5.0,<NA>,0.0,M-Pesa,Eldoret,<NA>,<NA>,<NA>
365,ORD12419,2024-08-13,Victor Cheruiyot,Maize Flour 2Kg,Groceries,14.0,<NA>,0.0,M-Pesa,Nakuru,<NA>,<NA>,<NA>
396,ORD12281,2024-11-26,Ann Njoroge,Soda 500Ml,Beverages,-13.0,<NA>,0.0,Card,Nakuru,<NA>,<NA>,<NA>
443,ORD11995,2024-07-17,Mary Wanjiru,Cooking Gas Refill 6Kg,Household,5.0,<NA>,0.0,Cash,Eldoret,<NA>,<NA>,<NA>
517,ORD15058,NaT,Naomi Wanjiru,Cooking Gas Refill 6Kg,Household,13.0,<NA>,0.0,Card,Thika,<NA>,<NA>,<NA>

In [85]:
df[df["unitprice"].isna()]["product"].value_counts(dropna=False)

product
Cooking Gas Refill 6Kg     41
Soda 500Ml                 17
Milk 500Ml                 14
Maize Flour 2Kg            13
Soap Bar                   12
Sugar 2Kg                  11
Exercise Book              10
Airtime Scratch Card       10
Cooking Oil 1L             10
Bottled Water 500Ml        10
Earphones                   9
Biscuits                    9
Phone Charger               8
Bread                       8
Bic Pen                     8
Umbrella                    7
Sweets Packet               5
Detergent 1Kg               4
Cooking Gas Re Fill 6Kg     2
Swe Ets Packet              2
Toothpaste                  2
Rice 2Kg                    1
De Tergent 1Kg              1
Name: count, dtype: Int64

In [86]:
price_check = df.groupby("product")["unitprice"].agg(
    ["count", "min", "max"]
)

price_check.loc[
    df.loc[df["unitprice"].isna(), "product"].dropna().unique()
]

                         count      min      max
product
Bread                      411    58.56    74.67
Sugar 2Kg                  430    234.1   298.77
Milk 500Ml                 438     54.0    68.98
Cooking Gas Re Fill 6Kg     16  1117.26  1359.99
Airtime Scratch Card       449    90.13   114.86
Maize Flour 2Kg            454   171.01   218.07
Soda 500Ml                 483     63.0     80.5
Cooking Gas Refill 6Kg     344  1080.38  1379.15
Exercise Book              450    40.51     52.0
Umbrella                   438    360.0   459.03
Bottled Water 500Ml        401     45.0    57.44
Detergent 1Kg              450   189.22   241.14
Soap Bar                   431    49.58    63.18
Earphones                  419   405.07   517.47
Sweets Packet              403     27.0    34.48
Phone Charger              423   315.01   402.49
Bic Pen                    410     18.0     23.0
Cooking Oil 1L             432   288.14   367.86
Biscuits                   437    81.15   103.48
Swe Ets Packet              21    27.02    34.11
Rice 2Kg                   471   252.16   321.96
De Tergent 1Kg              19   192.77    240.0
Toothpaste                 444    135.0   172.41

In [87]:
price_summary = df.groupby("product")["unitprice"].agg(
    ["count", "nunique", "mean"]
)

missing_products = df.loc[
    df["unitprice"].isna(), "product"
].dropna().unique()

price_summary.loc[missing_products]

                         count  nunique         mean
product
Bread                      411      354    66.560511
Sugar 2Kg                  430      409   266.823047
Milk 500Ml                 438      374    61.534201
Cooking Gas Re Fill 6Kg     16       16  1258.381875
Airtime Scratch Card       449      395    102.44049
Maize Flour 2Kg            454      427   193.841123
Soda 500Ml                 483      419    71.948054
Cooking Gas Refill 6Kg     344      342  1234.363081
Exercise Book              450      366    46.218933
Umbrella                   438      427   409.441142
Bottled Water 500Ml        401      344    51.215187
Detergent 1Kg              450      413   214.398822
Soap Bar                   431      361     56.42935
Earphones                  419      410   457.298831
Sweets Packet              403      313     30.71273
Phone Charger              423      411   358.959314
Bic Pen                    410      275    20.605366
Cooking Oil 1L             432      416   328.851898
Biscuits                   437      393    92.720503
Swe Ets Packet              21       21    30.595238
Rice 2Kg                   471      455   288.337749
De Tergent 1Kg              19       19   213.615263
Toothpaste                 444      419   154.394685

In [88]:
df[df["unitprice"].isna()][
    ["product", "date", "quantity"]
].head(20)

                      product       date  quantity
161                     Bread 2024-04-21      14.0
196                 Sugar 2Kg 2024-11-26      14.0
219                     Bread 2024-02-07       1.0
242                Milk 500Ml 2026-08-21      11.0
302   Cooking Gas Re Fill 6Kg 2025-11-17       4.0
305      Airtime Scratch Card 2026-03-10       5.0
365           Maize Flour 2Kg 2024-08-13      14.0
396                Soda 500Ml 2024-11-26     -13.0
443    Cooking Gas Refill 6Kg 2024-07-17       5.0
517    Cooking Gas Refill 6Kg        NaT      13.0
528             Exercise Book 2024-05-14       3.0
533    Cooking Gas Refill 6Kg 2026-06-12       2.0
545    Cooking Gas Refill 6Kg 2026-06-30       9.0
568    Cooking Gas Refill 6Kg 2026-02-03      11.0
642                  Umbrella 2025-08-07      10.0
680                 Sugar 2Kg 2026-08-08       3.0
712       Bottled Water 500Ml 2026-03-14       9.0
838                Soda 500Ml 2024-02-07      11.0
896             Exercise Book 2025-08-14       6.0
1029            Detergent 1Kg 2026-11-04      11.0

In [89]:
df[["quantity", "unitprice", "sales_amount",
    "discount_amount", "net_sales"]].isna().sum()

quantity           224
unitprice          214
sales_amount       434
discount_amount    434
net_sales          434
dtype: int64

In [90]:
print("Earliest date:", df["date"].min())
print("Latest date:", df["date"].max())

Earliest date: 2024-01-01 00:00:00
Latest date: 2026-12-09 00:00:00

In [91]:
df_time = df.dropna(subset=["date"]).copy()

df_time["month"] = df_time["date"].dt.to_period("M")

df_time.head()

,orderid,date,customername,product,category,quantity,unitprice,discount_percent,paymentmethod,region,sales_amount,discount_amount,net_sales,month
0,ORD16652,2026-06-05,Lucy Achieng,Soda 500Ml,Beverages,14.0,79.12,0.0,Card,Nakuru,1107.68,0.0,1107.68,2026-06
1,ORD14124,2024-07-29,Peter Cheruiyot,Toothpaste,Personal Care,2.0,151.16,0.0,Cash,Nairobi,302.32,0.0,302.32,2024-07
2,ORD12242,2025-11-25,Faith Gitau,Cooking Gas Re Fill 6Kg,Household,2.0,1358.01,0.0,Cash,Eldoret,2716.02,0.0,2716.02,2025-11
3,ORD16474,2024-02-21,Ruth Mwangi,Toothpaste,Personal Care,14.0,160.88,0.0,Cash,Mombasa,2252.32,0.0,2252.32,2024-02
4,ORD16243,2026-06-29,Unknown,Biscuits,Snacks,2.0,90.19,0.0,Cash,Eldoret,180.38,0.0,180.38,2026-06

In [92]:
df_time.shape

(8620, 14)

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
df.shape

(9000, 13)

In [95]:
df["sales_amount"].sum()

np.float64(13467715.419999994)

In [96]:
df["net_sales"].sum()

np.float64(13323478.114500005)